"""initial tables

Revision ID: 480815b0bb8f
Revises: 
Create Date: 2026-06-10 17:40:41.556441

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '480815b0bb8f'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('users',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('username', sa.String(length=100), nullable=False),
    sa.Column('email', sa.String(length=200), nullable=False),
    sa.Column('password', sa.String(length=255), nullable=False),
    sa.Column('role', sa.String(length=50), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email'),
    sa.UniqueConstraint('username')
    )
    op.create_table('excel_tables',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('columns', sa.JSON(), nullable=False),
    sa.Column('row_count', sa.Integer(), nullable=True),
    sa.Column('created_by', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['created_by'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('table_rows',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('table_id', sa.Integer(), nullable=False),
    sa.Column('row_index', sa.Integer(), nullable=False),
    sa.Column('data', sa.JSON(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['table_id'], ['excel_tables.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('table_rows', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_table_rows_table_id'), ['table_id'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('table_rows', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_table_rows_table_id'))

    op.drop_table('table_rows')
    op.drop_table('excel_tables')
    op.drop_table('users')
    # ### end Alembic commands ###
